### ISSUE TITLE
[study] Figure out how to print the minutes as pdf

### ISSUE THREAD

**Issue by ArtoLaitinen** [tablebook/tablebook#122]
No need to do any actual coding but research how it could be done and what library to use

**Comment by tuukkaviitanen** [comment]
[React PDF](https://react-pdf.org/) provides good PDF creation tools to React. It gives tools to render the PDFs with [PDFViewer component](https://react-pdf.org/components#pdfviewer) and a [download link component](https://react-pdf.org/components#pdfdownloadlink) for direct download without even rendering.

There is not a print dialogue action built into the library. We could use [ReactToPrint](https://www.npmjs.com/package/react-to-print) for achieving this functionality with React PDF.

This is the Gemini AI suggested snippet for using the react-to-print here. There is also a [live demo page](https://codesandbox.io/p/sandbox/magical-babycat-rzdhd?file=%2Fexamples%2FFunctionalComponent%2Findex.js) for ReactPDF.

```
import { useReactToPrint } from 'react-to-print';

const { ref } = useRef();

const handlePrint = useReactToPrint({
  content: () => ref.current,
});

return (
  <div style={{ display: 'none' }}>
    <div ref={ref}>
      {/* Your React PDF component */}
    </div>
  </div>
  <button onClick={handlePrint}>Print</button>
);

```

I suggest we try this on tablebook. The second option is just to use the download link in React PDF. User can open the PDF with browser PDF tools when clicking on the downloaded PDF.
