### ISSUE TITLE
style footer

### ISSUE THREAD

**Issue by vsuusi** [tablebook/tablebook#165]
Make footer look clean with icons instead of text. 
At least for github and copyright there are proper icons available,
For "report an issue" there could be icon + text, or maybe hover effect on icon to tell user what it does? or smth like dat

Does footer need background at all?

**Comment by tuukkaviitanen** [comment]
I think the texts should be there for clarity, but you could add icons to it to make it look nicer. 

You wouldn't notice the footer if it doesn't have a background.
