### ISSUE TITLE
fix the layout vertically

### ISSUE THREAD

**Issue by vsuusi** [tablebook/tablebook#94]
- fix layout vertically
- need to probably adjust components

Here is the problem: 
When screen is scaled verically, the layout breaks

![Image](https://github.com/tablebook/tablebook/assets/98397431/d1985cf1-c33f-4adf-b306-6e401b1681e9)

**Comment by tuukkaviitanen** [comment]
Try to utilize MUI breakpoints as much as possible to achieve scalability.

https://smartdevpreneur.com/5-mui-sx-breakpoint-examples/
